apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  containers:
    - name: jenkins
      image: mongo:latest
      ports:
      - containerPort: 27017
      env:
      - name: MONGO_OPTS
        value: "--prefix=/mongo"
      volumeMounts:
        - mountPath: "/var/mongo_home"
          name: mongo-home
  volumes:
    - name: mongo-home
      persistentVolumeClaim:
        claimName: mongo-home

